language: cpp
compiler:
  - gcc

# This is a lie: we don't need sudo but this is required to get an
# Ubuntu image with a libc that isn't ancient, and with cmocka libs.
sudo: required
dist: trusty

addons:
  apt:
    packages:

install: true

before_script:

script:
  - cd colorprint
  - gcc -o color colorprint.c colorprint.h
  - ./color
