language: c
compiler:
  - gcc

# This is a lie: we don't need sudo but this is required to get an
# Ubuntu image with a libc that isn't ancient, and with cmocka libs.
sudo: required
dist: trusty

addons:
  apt:
    packages:

install: true

before_script:

script:
    - ./bootstrap && ./configure
    - make
    - make check
    - cd test
    - python codecov.py gcno
    - python codecov.py exec
    - python codecov.py gcda
    - cd ..
    - for test_file in `ls ./test/test_*.c`; do gcov ${test_file}; done

after_success:
    - bash <(curl -s https://codecov.io/bash)
