#!/bin/sh
set -e

if [ ! -f .filelist ]; then
    echo `ls ./` > .filelist
fi
if [ -f Makefile ]; then
    make clean
    make distclean
    ./cleanup
fi

if [ "`uname -s`" = 'Darwin' ]; then
    alias libtoolize='glibtoolize'
    alias libtool='glibtool'
fi

printf "Running libtoolize......\n"
#libtoolize --install --force --copy --warnings=all
libtoolize --install --force --copy

printf "Running aclocal......\n"
aclocal -I /usr/local/share/aclocal

printf "Running autoconf......\n"
autoconf -I /usr/local/share/aclocal

printf "Running autoheader......\n"
autoheader

printf "Running automake......\n"
automake --add-missing
