#!/bin/bash
sources=(`cat .filelist`)

if [ -f Makefile ]; then
    make clean
    make distclean
fi

dir=(`ls .`)
for item in ${dir[@]}
do
    is_in=`[[ "${sources[@]/$item/}" != "${sources[@]}" ]] && echo "in"`
    if [ "$is_in" != "in" ]; then
        echo $item
        rm -irf $item
    fi
done
# cleanup test directory
rm -rf ./test/*.gcda
rm -rf ./test/*.gcno
