#!/bin/sh
set -x
sources="bootstrap \
         configure.ac \
         Makefile.am \
         LICENSE \
         README.md \
         cleanup \
         filelist \
         colorprint \
         include \
         test"

if [ -f Makefile ]; then
    make clean
    make distclean
fi

ls . > buff
for item in `echo "${sources}"| awk '{i=1; while(i<=NF) {print $i;i++}}'`
do
    sed -i '' "s/$item//g" buff
done
sed -i '' '/^$/d' buff

while read LINE
do
    rm -rf $LINE
done < buff
set +x
